default: install

install:
	code --install-extension CoenraadS.bracket-pair-colorizer && \
  code --install-extension dracula-theme.theme-dracula && \
	code --install-extension eamodio.gitlens && \
	code --install-extension esbenp.prettier-vscode && \
	code --install-extension kalitaalexey.vscode-rust && \
	code --install-extension ms-python.python && \
	code --install-extension ms-vscode.Go && \
	code --install-extension ms-vsliveshare.vsliveshare && \
	code --install-extension PeterJausovec.vscode-docker && \
	code --install-extension rust-lang.rust && \
	code --install-extension waderyan.gitblame && \
	code --install-extension wayou.vscode-todo-highlight && \
	code --install-extension whizkydee.material-palenight-theme && \
	code --install-extension wix.vscode-import-cost \